#creating order table
create table if not exists `ORDER`(
`ORD_ID` int not null primary key AUTO_INCREMENT ,
`ORD_AMOUNT` INT NOT NULL,
`ORD_DATE` DATE,
`CUS_ID` INT NOT NULL,
`PRICING_ID` INT NOT NULL,
FOREIGN KEY (`CUS_ID`) REFERENCES CUSTOMER (`CUS_ID`),
FOREIGN KEY (`PRICING_ID`) REFERENCES SUPPLIER_PRICING (`PRICING_ID`)
);